COMP: Fix RigidAlignement build error on unix due to invalid array
This commit fixes the following build error introduced by 7f0ac80(BUG:
Fix Windows crash on array allocation):

  In file included from /usr/include/c++/5/vector:62:0,
                   from ./RigidAlignmentCLP.h:8,
                   from /path/to/SlicerSALT/RigidAlignment/RigidAlignment.cxx:11:
  /usr/include/c++/5/bits/stl_construct.h: In instantiation of ‘void std::_Destroy(_Tp*) [with _Tp = std::__cxx11::basic_string<char> [250]]’:
  /usr/include/c++/5/bits/stl_construct.h:103:19:   required from ‘static void std::_Destroy_aux<<anonymous> >::__destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = std::__cxx11::basic_string<char> (*)[250]; bool <anonymous> = false]’
  /usr/include/c++/5/bits/stl_construct.h:127:11:   required from ‘void std::_Destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = std::__cxx11::basic_string<char> (*)[250]]’
  /usr/include/c++/5/bits/stl_construct.h:151:15:   required from ‘void std::_Destroy(_ForwardIterator, _ForwardIterator, std::allocator<_T2>&) [with _ForwardIterator = std::__cxx11::basic_string<char> (*)[250]; _Tp = std::__cxx11::basic_string<char> [250]]’
  /usr/include/c++/5/bits/stl_vector.h:424:22:   required from ‘std::vector<_Tp, _Alloc>::~vector() [with _Tp = std::__cxx11::basic_string<char> [250]; _Alloc = std::allocator<std::__cxx11::basic_string<char> [250]>]’
  /path/to/SlicerSALT/RigidAlignment/RigidAlignment.cxx:239:54:   required from here
  /usr/include/c++/5/bits/stl_construct.h:93:7: error: request for member ‘~std::__cxx11::basic_string<char> [250]’ in ‘* __pointer’, which is of non-class type ‘std::__cxx11::basic_string<char> [250]’
       { __pointer->~_Tp(); }
         ^
  ninja: build stopped: subcommand failed.
  FAILED: slicersources-build/RigidAlignment-prefix/src/RigidAlignment-stamp/RigidAlignment-build